{% set name = "asf_search" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 898d17909f9558fc4db2736373c1566eec06f618ed8c63f6b22b4530b370ab56

build:
  noarch: python
  number: 0

# This *really* shouldn't be necessary; see flailing here:
# https://github.com/conda-forge/asf_search-feedstock/pull/57
requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

outputs:
  - name: asf_search-base
    about:
      description: asf_search without any optional extra packages
    build:
      noarch: python
      script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=42
        - setuptools_scm >=3.4
        - wheel
      run:
        - python >=3.8
        - requests
        - shapely
        - pytz
        - importlib_metadata
        - numpy
        - dateparser
        - tenacity ==8.2.2
        - ciso8601
    test:
      imports:
        - asf_search
      requires:
        - pip
      commands:
        - pip check
        - "python -c 'from asf_search.download import download; assert download.RemoteZip is None'"

  - name: asf_search
    about:
      description: asf_search with all optional extra packages
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - remotezip >=0.10.0
        - {{ pin_subpackage('asf_search-base', max_pin="x.x.x") }}
    test:
      imports:
        - asf_search
      commands:
        - "python -c 'from asf_search.download import download; assert download.RemoteZip is not None'"

about:
  home: https://github.com/asfadmin/Discovery-asf_search
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for ASF's SearchAPI

extra:
  feedstock-name: asf_search
  recipe-maintainers:
    - jhkennedy
    - glshort
    - Cameronsplaze
    - williamh890
    - SpicyGarlicAlbacoreRoll
