{% set name = "asf_search" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45128f8b12a7b2b67dee9dffcd043f9582e76462dce0f5f095156501fd568596

build:
  noarch: python
  number: 1

# This *really* shouldn't be necessary; see flailing here:
# https://github.com/conda-forge/asf_search-feedstock/pull/57
requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

outputs:
  - name: asf_search-base
    about:
      description: asf_search without any optional extra packages
    build:
      noarch: python
      script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=42
        - setuptools_scm >=3.4
        - wheel
      run:
        - python >={{ python_min }}
        - requests
        - shapely
        - pytz
        - importlib_metadata
        - numpy
        - dateparser
        - tenacity ==8.2.2
        - ciso8601
    test:
      imports:
        - asf_search
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
        - "python -c 'from asf_search.download import download; assert download.RemoteZip is None'"

  - name: asf_search
    about:
      description: asf_search with all optional extra packages
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - remotezip >=0.10.0
        - {{ pin_subpackage('asf_search-base', max_pin="x.x.x") }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - asf_search
      commands:
        - "python -c 'from asf_search.download import download; assert download.RemoteZip is not None'"

about:
  home: https://github.com/asfadmin/Discovery-asf_search
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for ASF's SearchAPI

extra:
  feedstock-name: asf_search
  recipe-maintainers:
    - jhkennedy
    - glshort
    - Cameronsplaze
    - williamh890
    - SpicyGarlicAlbacoreRoll
