{% set name = "asf_search" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8670432a95959af4a98d6cbeb1f016e47614e280685f5648293a4f9161b795e2

build:
  number: 1

outputs:
  - name: asf_search-base
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=42
        - setuptools_scm >=3.4
        - wheel
      run:
        - python >=3.8
        - requests
        - shapely
        - python-dateutil
        - pytz
        - importlib_metadata
        - numpy
        - dateparser
        - tenacity ==8.2.2
    test:
      imports:
        - asf_search
      requires:
        - pip
      commands:
        - pip check
        - python -c 'from asf_search.download import download; assert download.RemoteZip is None'

  - name: asf_search
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - remotezip >=0.10.0
        - {{ pin_subpackage('asf_search-base', max_pin="x.x.x") }}
    test:
      imports:
        - asf_search
      commands:
        - python -c 'from asf_search.download import download; assert download.RemoteZip is not None'

about:
  home: https://github.com/asfadmin/Discovery-asf_search
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for ASF's SearchAPI

extra:
  recipe-maintainers:
    - jhkennedy
    - glshort
    - Cameronsplaze
    - williamh890
    - SpicyGarlicAlbacoreRoll
